StudentResources/Models/Course.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace StudentResources.Models
{
    public class Course
    {
        public int CourseId { get; set; }
        public string CourseName { get; set; }
        public string CourseUnits { get; set; }
        public int UnitId { get; set; }
        public string UnitSpecification { get; set; }
        public int UnitTeacherId { get; set; }
        public string TeacherName { get; set; }
        public bool Approval { get; set; }
    }

}

StudentResources/Models/ErrorViewModel.cs
using System;

namespace StudentResources.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

StudentResources/Models/RequestModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace StudentResources.Models
{
    public class RequestModel
    {
        public int RequestId { get; set; }
        public int StudentId { get; set; }
        public int ResourceId { get; set; }
        public bool Approval { get; set; }

    }
}

StudentResources/Models/ResourceModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace StudentResources.Models
{
    public class ResourceModel
    {   
        public int ResourceId { get; set; }
        public string ResourceName { get; set; }
        public string ResourceType { get; set; }
        public bool ResourceAvailability { get; set; }
        public int ResourceQuantity { get; set; }

    }

}

StudentResources/Models/StudentModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace StudentResources.Models
{
    public class StudentModel
    {
        public int StudentId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public string Contact { get; set; }
    }

}

StudentResources/Models/UserModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace StudentResources.Models
{
    public class UserModel
    {
        public int id { get; set; }

        public string username { get; set; }

        public string password { get; set; }

    }
}

StudentResources/Controllers/CourseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace StudentResources.Controllers
{
    public class CourseController : Controller
    {
        public IActionResult Course()
        {
            return View();
        }
    }
}

StudentResources/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using StudentResources.Models;

namespace StudentResources.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Login()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        public List<UserModel> PutValue()
        {
            var users = new List<UserModel>
            {
                new UserModel{id=1,username="Sushil",password="abc123"},
                new UserModel{id=2,username="Shital",password="xyz546"},
                new UserModel{id=3,username="Suman",password="pnpc465"},
                new UserModel{id=4,username="Sujan",password="urt324"}
            };

            return users;
        }

        [HttpPost]
        public IActionResult Verify(UserModel usr)
        {
            var u = PutValue();

            var ue = u.Where(u => u.username.Equals(usr.username));

            var up = ue.Where(p => p.password.Equals(usr.password));

            if (up.Count() == 1)
            {
                ViewBag.message = "Login Success";
                return View("LoginSuccess");
            }
            else
            {
                ViewBag.message = "Login Failed";
                return View("Login");
            }
        }
    }
}

StudentResources/Controllers/RequestController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace StudentResources.Controllers
{
    public class RequestController : Controller
    {
        public IActionResult Reequest()
        {
            return View();
        }
    }
}

StudentResources/Controllers/ResourceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using StudentResources.Models;

namespace StudentResources.Controllers
{
    public class ResourceController : Controller
    {
        List<ResourceModel> resource = new List<ResourceModel>()
        {
               new ResourceModel { ResourceId = 1, ResourceName = "Laptop", ResourceType = "Level 1 Valuable", ResourceAvailability = true, ResourceQuantity = 100 },
               new ResourceModel { ResourceId = 2, ResourceName = "Android", ResourceType = "Level 2 Valuable", ResourceAvailability = false, ResourceQuantity = 50},
               new ResourceModel { ResourceId = 3, ResourceName = "Iphone", ResourceType = "Level 1 Valuable", ResourceAvailability = true, ResourceQuantity = 200},
               new ResourceModel { ResourceId = 4, ResourceName = "Tablet", ResourceType = "Level 2 Valuable", ResourceAvailability = false, ResourceQuantity = 40}
        };

        // GET: Person
        public ActionResult Index()
        {
            return View(resource);
        }
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(ResourceModel per)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return View("Create", per);
                }
                resource.Add(per);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        public ActionResult Details(int id)
        {
            ResourceModel per = resource.Find(res => res.ResourceId == id);
            return View(per);
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            ResourceModel per = resource.Find(res => res.ResourceId == id);
            return View(per);
        }

        public ActionResult Delete()
        {
            return View();
        }
    }
}

StudentResources/Controllers/StudentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using StudentResources.Models;

namespace StudentResources.Controllers
{
    public class StudentController : Controller
    {
        List<StudentModel> student = new List<StudentModel>()
        {
               new StudentModel {StudentId = 0012, FirstName ="Sushil", LastName="Shakya", Email="email@gmail.com", Address="abc st nsw", Contact = "00123212"}
              
        };
        public ActionResult Index()
        {
            return View(student);
        }

        [HttpGet]
        public ActionResult Detail(int id)
        {
            StudentModel per = student.Find(res => res.StudentId == id);
            return View(per);
        }
    }
}

StudentResources/Views/Course/Course.cshtml

@{
    ViewData["Title"] = "Course";
}

<head>
    <style>
        body {
            margin: 0;
            padding: 0;
            background-color: #e0ffff;
            height: 100vh;
        }
    </style>
</head>
<h1>Course</h1>

<!DOCTYPE html>
<html>
<body>

    <h1>Check Resource Requirements</h1>

    <form action="/action_page.php" method="post" target="_blank">


        <label>Choose a Course:</label>

        <select>
            <option>NIT123</option>
            <option>CDE456</option>
            <option>FGH789</option>
            <option>IJK012</option>
            <option>NIT123</option>
            <option>CDE456</option>
            <option>FGH789</option>
            <option>IJK012</option>
        </select><br><br>

        <label>Choose Unit of this Course:</label>

        <select>
            <option>NIT123</option>
            <option>NIT456</option>
            <option>NIT789</option>
            <option>NIT012</option>
            <option>NIT123</option>
            <option>NIT456</option>
            <option>NIT789</option>
            <option>NIT012</option>
        </select><br><br>

        <input type="submit" value="Check Requirement"><br><br>
    </form>

    <p>You have following Resources Required for this Unit</p>
    <li>
        <ol>Laptop: Windows Version</ol>
    </li>

</body>
</html>


StudentResources/Views/Home/Login.cshtml

@model StudentResources.Models.UserModel;
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome to Student Resources</h1>
    <p>Please Login to Explore</p>
</div>

<!DOCTYPE html>
<html>
<head>
        <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
        <style>
                    body {
            margin: 0;
            padding: 0;
            background-color: #e0ffff;
            height: 100vh;
        }

        #login .container #login-row #login-column #login-box {
            margin-top: 120px;
            max-width: 400px;
            height: 350px;
            border: 1px solid #9C9C9C;
            background-color: #EAEAEA;
        }

            #login .container #login-row #login-column #login-box #login-form {
                padding: 20px;
            }

                #login .container #login-row #login-column #login-box #login-form #register-link {
                    margin-top: -85px;
                }

    </style>


</head>
<body>

    <div id="login">
        <div class="container">
            <div id="login-row" class="row justify-content-center align-items-center">
                <div id="login-column" class="col-md-6">
                    <div id="login-box" class="col-md-12">
                        @using (Html.BeginForm("Verify", "Login", FormMethod.Post))
                        {<h3 class="text-center text-info">Login</h3>
                            <div class="form-group">
                                <label for="username" class="text-info">Username:</label><br>
                                @Html.TextBoxFor(m => m.username, new { @class = "form-control", @placeholder = "Username", @required = true })
                            </div>
                            <div class="form-group">
                                <label for="password" class="text-info">Password:</label><br>
                                @Html.PasswordFor(m => m.password, new { @class = "form-control", @placeholder = "Password", @required = true })
                            </div>
                            <div class="form-group">
                                <label for="remember-me" class="text-info"><span>Remember me</span> <span><input id="remember-me" name="remember-me" type="checkbox"></span></label><br>
                                <input type="submit" name="submit" class="btn btn-info btn-md" value="submit">
                            </div>
                        }
                        <div style="color:red;">@ViewBag.message</div>
                    </div>
                </div>
            </div>
        </div>
    </div>

</body>
</html>

StudentResources/Views/Home/LoginSuccess.cshtml

@{
    ViewData["Title"] = "LoginSuccess";
}


<html>
<head>
    <title>Login Success</title>
    <style>
        #aa {
            border-radius: 25px;
            border: 2px solid red;
            padding: 50px 125px;
            width: 250px;
            height: 100px;
            color: forestgreen;
            text-align: center;
            font-size: 25px;
            margin-left: 30%;
        }
    </style>
</head>
<body>
    <div id="aa">@ViewBag.message</div>
</body>
</html>

StudentResources/Views/Request/Reequest.cshtml
@model StudentResources.Models.UserModel;
@{
    ViewData["Title"] = "Reequest";
}

<head>
    <style>
        body {
            margin: 0;
            padding: 0;
            background-color: #e0ffff;
            height: 100vh;
        }
    </style>
</head>
<div class="text-center">
    <h1 class="display-4">Request Resources</h1>
    <p>Please fillup the request form and submit</p>
</div>


<!DOCTYPE html>
<html>
<body>

    <h1>Request Form</h1>

    <form action="/action_page.php" method="post" target="_blank">

        <label>Student Id:</label>
        <input type="text"><br><br>

        <label>Student Email:</label>
        <input type="text"><br><br>

        <label>Choose a Course:</label>

        <select>
            <option>NIT123</option>
            <option>CDE456</option>
            <option>FGH789</option>
            <option>IJK012</option>
        </select><br><br>

        <label>Choose Unit of this Course:</label>

        <select>
            <option>NIT123</option>
            <option>NIT456</option>
            <option>NIT789</option>
            <option>NIT012</option>
        </select><br><br>

        <label>Choose Resource:</label>

        <select>
            <option>Laptop</option>
            <option>Tablet</option>
            <option>Android</option>
            <option>Iphone</option>
        </select><br><br>

        <label for="start">Request date:</label>
        <input type="date"
               value="2020-07-22"
               min="2022-07-01" max="2025-07-31"><br><br>

        <label for="week">Select a week:</label>
        <input type="week"><br><br>

<textarea name="comment" form="usrform">Any comments...</textarea><br><br>

        <input type="submit" value="Request"><br><br>
    </form>

    <p>Click on request so that your request will be sent to your unit teacher</p>

</body>
</html>


StudentResources/Views/Resource/Create.cshtml
@model StudentResources.Models.ResourceModel

@{
    ViewBag.Title = "Create";
}

<head>
    <style>
        body {
            margin: 0;
            padding: 0;
            background-color: #e0ffff;
            height: 100vh;
        }
    </style>
</head>
<h2>Create</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>ResourceModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ResourceName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ResourceName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ResourceName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ResourceType, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ResourceType, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ResourceType, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ResourceAvailability, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.ResourceAvailability)
                    @Html.ValidationMessageFor(model => model.ResourceAvailability, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>


StudentResources/Views/Resource/Details.cshtml
@model StudentResources.Models.ResourceModel

@{
    ViewBag.Title = "Details";
}

<head>
    <style>
        body {
            margin: 0;
            padding: 0;
            background-color: #e0ffff;
            height: 100vh;
        }
    </style>
</head>

<h2>Details</h2>

<div>
    <h4>ResourceModel</h4>
    <hr />
    <dl class="dl-horizontal">

        <dt>
            @Html.DisplayNameFor(model => model.ResourceName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ResourceName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ResourceType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ResourceType)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ResourceAvailability)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ResourceAvailability)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ResourceQuantity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ResourceQuantity)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ResourceId }) |
    @Html.ActionLink("Back to List", "Index")
</p>


StudentResources/Views/Resource/Edit.cshtml
@model StudentResources.Models.ResourceModel

@{
    ViewBag.Title = "Edit";
}

<head>
    <style>
        body {
            margin: 0;
            padding: 0;
            background-color: #e0ffff;
            height: 100vh;
        }
    </style>
</head>

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Resource</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ResourceId)

        <div class="form-group">
            @Html.LabelFor(model => model.ResourceName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ResourceName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ResourceName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ResourceType, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ResourceType, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ResourceType, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ResourceAvailability, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.ResourceAvailability)
                    @Html.ValidationMessageFor(model => model.ResourceAvailability, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>


StudentResources/Views/Resource/Index.cshtml
@model IEnumerable<StudentResources.Models.ResourceModel>

@{
    ViewBag.Title = "Index";
}

<head>
    <style>
        body {
            margin: 0;
            padding: 0;
            background-color: #e0ffff;
            height: 100vh;
        }
    </style>
</head>


<h2>Resources</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ResourceName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ResourceType)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ResourceAvailability)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ResourceQuantity)
        </th>>

    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ResourceName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ResourceType)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ResourceAvailability)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ResourceQuantity)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.ResourceId }) |
                @Html.ActionLink("Details", "Details", new { id = item.ResourceId }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.ResourceId })
            </td>
        </tr>
    }

</table>


StudentResources/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - StudentResources</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">StudentResources</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Login">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Student" asp-action="Index">Student Detail</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Request" asp-action="Reequest">Request</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Resource" asp-action="Index">Resource</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Course" asp-action="Course">Course</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - StudentResources - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

StudentResources/Views/Student/Detail.cshtml
@model StudentResources.Models.StudentModel

@{
    ViewBag.Title = "Detail";
}

<head>
    <style>
        body {
            margin: 0;
            padding: 0;
            background-color: #e0ffff;
            height: 100vh;
        }
    </style>
</head>

<h2>Details</h2>

<div>
    <h4>StudentModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.StudentId): @Html.DisplayFor(model => model.StudentId)
        </dt>

        <dt>
            @Html.DisplayNameFor(model => model.FirstName): @Html.DisplayFor(model => model.FirstName)
        </dt>

        <dt>
            @Html.DisplayNameFor(model => model.LastName): @Html.DisplayFor(model => model.LastName)
        </dt>
        <dt>
            @Html.DisplayNameFor(model => model.Email): @Html.DisplayFor(model => model.Email)
        </dt>
        <dt>
            @Html.DisplayNameFor(model => model.Address): @Html.DisplayFor(model => model.Address)
        </dt>
        <dt>
            @Html.DisplayNameFor(model => model.Contact): @Html.DisplayFor(model => model.Contact)
        </dt>

    </dl>
</div>
<p>
    @Html.ActionLink("Back to data", "Index")

</p>


StudentResources/Views/Student/Index.cshtml
@model IEnumerable<StudentResources.Models.StudentModel>

@{
    ViewBag.Title = "Index";
}

<head>
    <style>
        body {
            margin: 0;
            padding: 0;
            background-color: #e0ffff;
            height: 100vh;
        }
    </style>
</head>

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.StudentId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LastName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        <th>
            @Html.DisplayNameFor(model => model.Address)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Contact)
        </th>
        </th>>

    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.StudentId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Address)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Contact)
            </td>
            <td>

                @Html.ActionLink("Detail", "Detail", new { id = item.StudentId })

            </td>
        </tr>
    }

</table>